### PR TITLE
Import RNNCellBase from torch.nn.modules.rnn

### LINKED ISSUE #13: ortho_init doesn't work with PyTorch 0.4.1
When trying to run VAE example got this:
```
Traceback (most recent call last):
  File "/Users/dkorduban/.pyenv/versions/3.6.1/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/dkorduban/.pyenv/versions/3.6.1/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dkorduban/workspace/sc2/lagom/lagom/core/multiprocessing/base_worker.py", line 47, in __call__
    task_id, result = self.work(master_cmd)
  File "/Users/dkorduban/workspace/sc2/lagom/lagom/experiment/base_experiment_worker.py", line 55, in work
    result = algo(config, seed, device_str=device_str)
  File "/Users/dkorduban/workspace/sc2/lagom/examples/vae/algo.py", line 58, in __call__
    model = ConvVAE(config=config)
  File "/Users/dkorduban/workspace/sc2/lagom/lagom/core/networks/base_network.py", line 66, in __init__
    self.init_params(self.config)
  File "/Users/dkorduban/workspace/sc2/lagom/examples/vae/network.py", line 107, in init_params
    ortho_init(layer, nonlinearity='relu', constant_bias=0.0)
  File "/Users/dkorduban/workspace/sc2/lagom/lagom/core/networks/init.py", line 34, in ortho_init
    if isinstance(module, (nn.RNNBase, nn.RNNCellBase)):  # RNN
AttributeError: module 'torch.nn' has no attribute 'RNNCellBase'
```
```
Dmytros-MacBook-Pro:vae dkorduban$ pip freeze | grep torch
torch==0.4.1
torchvision==0.2.1
```

### PR DESCRIPTION
**Pull request by dkorduban**
Fixes #13

### CODE REVIEW

**Comment by zuoxingdong** [comment]
Thank you @dkorduban for the contribution !
